
export class aaAutorec {
    static get defaultConfiguration() {
        const defaultConfig = {
            search: "",
            melee: {
                0: {
                    hidden: true,
                    name: 'Dagger',
                    animation: 'dagger',
                    variant: '01',
                    color: 'white',
                    repeat: 1,
                    delay: 500,
                    scale: 1,
                },
                1: {
                    hidden: true,
                    name: 'Flurry of Blows',
                    animation: 'flurryofblows',
                    variant: 'physical',
                    color: 'blue',
                    repeat: 1,
                    delay: 500,
                    scale: 1,
                },
                2: {
                    hidden: true,
                    name: 'Greataxe',
                    animation: 'greataxe',
                    variant: '01',
                    color: 'white',
                    repeat: 1,
                    delay: 500,
                    scale: 1,
                },
                3: {
                    hidden: true,
                    name: 'Greatclub',
                    animation: 'greatclub',
                    variant: '01',
                    color: 'white',
                    repeat: 1,
                    delay: 500,
                    scale: 1,
                },
                4: {
                    hidden: true,
                    name: 'Greatsword',
                    animation: 'greatsword',
                    variant: '01',
                    color: 'white',
                    repeat: 1,
                    delay: 500,
                    scale: 1,
                },
                5: {
                    hidden: true,
                    name: 'Handaxe',
                    animation: 'handaxe',
                    variant: '01',
                    color: 'white',
                    repeat: 1,
                    delay: 500,
                    scale: 1,
                },
                6: {
                    hidden: true,
                    name: 'Longsword',
                    animation: 'sword',
                    variant: '01',
                    color: 'white',
                    repeat: 1,
                    delay: 500,
                    scale: 1,
                },
                7: {
                    hidden: true,
                    name: 'Mace',
                    animation: 'mace',
                    variant: '01',
                    color: 'white',
                    repeat: 1,
                    delay: 500,
                    scale: 1,
                },
                8: {
                    hidden: true,
                    name: 'Maul',
                    animation: 'maul',
                    variant: '01',
                    color: 'white',
                    repeat: 1,
                    delay: 500,
                    scale: 1,
                },
                9: {
                    hidden: true,
                    name: 'Shortsword',
                    animation: 'sword',
                    variant: '01',
                    color: 'white',
                    repeat: 1,
                    delay: 500,
                    scale: 1,
                },
                10: {
                    hidden: true,
                    name: 'Spear',
                    animation: 'spear',
                    variant: '01',
                    color: 'white',
                    repeat: 1,
                    delay: 500,
                    scale: 1,
                },
                11: {
                    hidden: true,
                    name: 'Rapier',
                    animation: 'rapier',
                    variant: '01',
                    color: 'white',
                    repeat: 1,
                    delay: 500,
                    scale: 1,
                },
                12: {
                    hidden: true,
                    name: 'Unarmed Strike',
                    animation: 'unarmedstrike',
                    variant: 'physical',
                    color: 'blue',
                    repeat: 1,
                    delay: 500,
                    scale: 1,
                },
            },
            range: {
                0: {
                    hidden: true,
                    name: 'Crossbow',
                    animation: 'bolt',
                    variant: 'physical',
                    color: 'orange',
                    repeat: 1,
                    delay: 500,
                    type: "weapon",
                },
                1: {
                    hidden: true,
                    name: 'Longbow',
                    animation: 'arrow',
                    variant: 'regular',
                    color: 'regular',
                    repeat: 1,
                    delay: 500,
                    type: "weapon",
                },
                2: {
                    hidden: true,
                    name: 'Shortbow',
                    animation: 'arrow',
                    variant: 'regular',
                    color: 'regular',
                    repeat: 1,
                    delay: 500,
                    type: "weapon",
                },
                3: {
                    hidden: true,
                    name: 'Disintegrate',
                    animation: 'disintegrate',
                    variant: '01',
                    color: 'green',
                    repeat: 1,
                    delay: 500,
                    type: "spell",
                },
                4: {
                    hidden: true,
                    name: 'Eldritch Blast',
                    animation: 'eldritchblast',
                    variant: '01',
                    color: 'purple',
                    repeat: 1,
                    delay: 500,
                    type: "spell",
                },
                5: {
                    hidden: true,
                    name: 'Fire Bolt',
                    animation: 'firebolt',
                    variant: '01',
                    color: 'orange',
                    repeat: 1,
                    delay: 500,
                    type: "spell",
                },
                6: {
                    hidden: true,
                    name: 'Guiding Bolt',
                    animation: 'guidingbolt',
                    variant: '01',
                    color: 'blueyellow',
                    repeat: 1,
                    delay: 500,
                    type: "spell",
                },
                7: {
                    hidden: true,
                    name: 'Magic Missile',
                    animation: 'magicmissile',
                    variant: '01',
                    color: 'purple',
                    repeat: 3,
                    delay: 500,
                    type: "spell",
                },
                8: {
                    hidden: true,
                    name: 'Ray of Frost',
                    animation: 'rayoffrost',
                    variant: '01',
                    color: 'blue',
                    repeat: 1,
                    delay: 500,
                    type: "spell",
                },
                9: {
                    hidden: true,
                    name: 'Scorching Ray',
                    animation: 'scorchingray',
                    variant: '01',
                    color: 'orange',
                    repeat: 1,
                    delay: 500,
                    type: "spell",
                },
                10: {
                    hidden: true,
                    name: 'Witch Bolt',
                    animation: 'witchbolt',
                    variant: '01',
                    color: 'blue',
                    repeat: 1,
                    delay: 500,
                    type: "spell",
                },
            },
            static: {
                0: {
                    hidden: true,
                    name: 'Cure Wounds',
                    animation: 'curewounds',
                    variant: '01',
                    color: 'blue',
                    repeat: 1,
                    delay: 500,
                    scale: 1.5,
                    below: true,
                    type: "targetDefault",
                },
                1: {
                    hidden: true,
                    name: 'Healing Word',
                    animation: 'generichealing',
                    variant: '01',
                    color: 'blue',
                    repeat: 1,
                    delay: 500,
                    scale: 1.5,
                    below: true,
                    type: "targetDefault",
                },
                2: {
                    hidden: true,
                    name: 'Toll the Dead',
                    animation: 'generichealing',
                    variant: '01',
                    color: 'blue',
                    repeat: 1,
                    delay: 500,
                    scale: 1,
                    below: true,
                    type: "target",
                }
            },
            templates: {
                0: {
                    animation: "calllightning",
                    below: false,
                    color: 'blueorange',
                    custom: false,
                    delay: 500,
                    hidden: true,
                    name: "Call Lightning",
                    occlusionAlpha: 0.7,
                    occlusionMode: "3",
                    opacity: 0.75,
                    overhead: true,
                    persist: true,
                    removeTemplate: true,
                    repeat: 1,
                    type: 'circle',
                    variant: '01',
                },
                1: {
                    animation: "fogcloud",
                    below: false,
                    color: 'white',
                    custom: false,
                    delay: 500,
                    hidden: true,
                    name: "Fog Cloud",
                    occlusionAlpha: 0.65,
                    occlusionMode: "3",
                    opacity: 0.75,
                    overhead: true,
                    persist: true,
                    removeTemplate: true,
                    repeat: 1,
                    type: 'circle',
                    variant: '01',
                },
            },
            auras: {
                0: {
                    animation: "spiritguardians",
                    below: false,
                    color: 'darkblue',
                    custom: false,
                    hidden: true,
                    name: "Spirit Guardians",
                    opacity: 0.75,
                    scale: 7,
                    static: false,
                    tint: '#ffffff',
                    variant: '01',
                    ignoretargets: true,
                },
            },
            preset: {
                0: {
                    animateSelf: true,
                    animateTarget: true,
                    animation: "bardicinspiration",
                    below: false,
                    hidden: true,
                    marker: true,
                    name: "Bardic Inspiration",
                    scale: 1,
                    selfAnimation: "music",
                    selfColor: "blue",
                    selfMarkerColor: "greenorange",
                    targetAnimation: "bardicinspiration",
                    targetColor: "greenorange",
                    targetMarkerColor: "greenorange",
                },
                1: {
                    addCTA: false,
                    animation: "bless",
                    below: true,
                    color: "yellow",
                    hidden: true,
                    name: "Bless",
                    scale: 1.5,
                },
                2: {
                    animation: "shieldspell",
                    below: false,
                    color: "blue",
                    endeffect: "outro_explode",
                    hidden: true,
                    name: "Shield",
                    scale: 1,
                    variant: "01",
                },
                3: {
                    animation: "teleportation",
                    below: false,
                    color: "blue",
                    custom: false,
                    hidden: true,
                    hideTemplate: false,
                    name: "Misty Step",
                    range: 30,
                    scale: 1.5,
                    subAnimation: "mistystep",
                }
            }
        };
        return defaultConfig;
    }

    constructor() {
        this._enabled = false;
    }
}

export const dnd5eAutoRec = new aaAutorec();